image: docker:latest
services:
- docker:dind

stages:
- build
- release

variables:
  TEST_IMAGE: gitlab.brigzzy.net:5555/brigzzy/metamagic-helper:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: gitlab.brigzzy.net:5555/brigzzy/metamagic-helper:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.brigzzy.net:5555

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master
