# version: '2'
# Use root/example as user/password credentials
version: '2'

services:

  db:
    build: ./sql
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz0okM

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: ./web
    restart: always
    ports:
     - 80:80
